config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  
  resources :games

  root 'users#index'
  
  resources :users 
  resources :teams
  resources :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :user_teams
  has_many :teams, through: :user_teams
  has_many :games, through: :teams

  has_many :post_games
  has_many :games, through: :post_games
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to current_user
  end 

  def create
  end 

  def show
    @user = User.find(params[:id])
    games = @user.teams.map do |team|
                team.games.map do |game|
                  game
                end 
             end 
    @games = games.flatten
    @games << @user.games
    @games = @games.flatten
    @games = @games.uniq
  end 

  def update
    @user = User.find(params[:id])
    @game = Game.where(:game_info => params[:games_not_attending][:game_info])
    @user.games_not_attending << @game[0].id
    @user.save

    @post = Post.create(:title => @game[0].game_info)
    @user.posts << @post
    @game[0].posts << @post
    redirect_to current_user
  end 
  # private
  # def user_params
  #   params.require(:user).permit(:user => [:name, :age, :height, :weight, :bio])
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notAttending.html.erb
<div class='attending_container'>
  <div class='close_out'>X</div>
  <div class='not_attending'>
    <%= form_tag({controller: "users", action: "update"}, method: "patch") do |f|%>
      <input type="text" value="" name="games_not_attending[game_info]" class="games_not_attending_game_info"><br>
      <input type="submit" value="I Can't Make It">
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 

app/views/users/show.html.erb
<%= render partial: "nav.html" %>
<div class="user_container">
<!-- NAV DROPDOWN WITH USERS TEAM -->
<div class="nav_dropdown">
  <% @user.teams.each do |team_object| %>
    <div class="nav_tile">
      <a href=<%="/teams/"+team_object.id.to_s%>> <%= team_object.name %> </a>
    </div> 
  <% end %>
  <div class="nav_tile">
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </div>
</div>

  <!-- USER-NAME -->
  <div class="user_name_container">
    <h1 class="user_name"><%= @user.name %></h1>
  </div>

  <div class="join_create_team_container">
  <!-- BUTTONS -->
    <div class="join_team">
      <!-- JOIN TEAM  -->
      <div id="join_team_form_button">Join Team</div>
        <div id="join_team_form">
          <%= form_tag({controller: "teams", action: "edit"}, method: "get") do |f|%>
            <label for="team_id_input">Enter Team Code</label>
            <input type="text" value="" name="team_id[id]" id="team_id_input"><br>
            <input type="submit" value="Join Team">
          <% end %> 
        </div>
    </div>

    <!-- TEAM CREATE -->
    <!-- <div class="join_team"> -->
    <div class="create_team">
      <div id="team_create_form_button"><%= link_to "New Team", new_team_path %></div>
      <div id="team_create_form">

        <%= form_tag({controller: "teams", action: "create"}, method: "post") do |f|%>
          <label for="team_name">Name</label>
          <input type="text" value="" name="team[name]" id="team_name"><br>
          <div class="game_form">
            <label for="team_sport_id">Sport: </label>
            <%= collection_select(:team, :sport_id, Sport.all, :id, :name, prompt: true) %>
          </div>
          <div class="player_form">
              <label for="team_roster">Add Teammate Emails</label>
              <input type="text" value="" name="team[roster][]" id="team_roster"><br>
          </div>
          <a class="player_button">Add Email</a><br>
          <input type="submit" value="Create">
          <div class="hidden">
            <input type="text" value=<%= @user.id %> name="team[user_id]" id="team_games" >
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  
  <!-- CREATE A TEAM -->
  

<div class="calendar_container">
  <div class="calendar">
  <% if @games.count == 0 %>
    <%= month_calendar events: @games, day_names: "date.day_names" do |date, games| %>
    <% if games.length == 0 %>
          <div class="cal_date_no_game"><%= date.day %></div>
    <% end %>
  <% end %>
  <% end %>
    <% if @games.count > 0 %>
      <%= month_calendar events: @games, day_names: "date.day_names" do |date, games| %>
      <% if games.length == 0 %>
            <div class="cal_date_no_game"><%= date.day %></div>
      <% end %>
      <!-- IF ANY GAME ARE PRESENT MAKE CONTAINER -->
      <% if games.length>0 %>
          <div class="cal_date"><%= date.day %></div>
      <% end %>
      <!-- ITERATION: populate cal days with game icon and info -->
        <% if games.length > 0 %>
        <% games.each do |game| %>
            <% if @user.games_not_attending.include?(game.id.to_s) %>
            <% else %>
            
                <div class="game_attendance">
                <img class=<%= game.team.sport.name %> src="">
                
                <div class='attending_container'>
                <div class='close_out'>X</div>
                <!-- FORM -->
                    <div class='not_attending'>
                      <%= form_tag({controller: "users", action: "update"}, method: "patch") do |f|%>
                        <input type="text" value="" name="games_not_attending[game_info]" class="games_not_attending_game_info"><br>
                        <input type="submit" value="I Can't Make It">
                      <% end %>
                    </div>
                <!-- END FORM -->
              </div>

                <div class="calendar_game_info">
                      <p><%= game.game_info %><br></p>
                      <p><%= game.game_time.strftime("%I:%M%p") %><br></p>
                      <p><%= game.location %><br></p> 
                </div>
                </div>
            
            <% end %>
          <% end %>
          <% end %>
      <% end %>
  <% end %>
  </div>
</div>