config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}
  
  resources :games

  root 'users#index'
  
  resources :users 
  resources :teams
  resources :posts

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :team
  has_many :posts
  has_many :users, through: :teams

  has_many :post_games
  has_many :users, through: :post_games

  extend SimpleCalendar
  has_calendar :attribute => :game_date

  attr_accessor :roster


end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  has_one :team, through: :user
end

app/models/post_game.rb
class PostGame < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/sport.rb
class Sport < ActiveRecord::Base
 
  has_many :teams

  has_many :users, through: :teams
  has_many :posts, through: :users # ?
  
end

app/models/team.rb
require 'securerandom'
class Team < ActiveRecord::Base

  has_many :games
  belongs_to :sport
  
  
  has_many :user_teams
  has_many :users, through: :user_teams
  has_many :posts, through: :users

  def random_id
    array = Team.all.map {|team| team.hex_id}
    code = SecureRandom.hex[0..3]
    while array.include?(code)
      code = SecureRandom.hex[0..3]
    end
    code
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :user_teams
  has_many :teams, through: :user_teams
  has_many :games, through: :teams

  has_many :post_games
  has_many :games, through: :post_games
end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :age, :height, :weight, :bio, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :age, :height, :weight, :bio, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :age, :height, :weight, :bio, :email, :password, :password_confirmation, :remember_me) }
  end 
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def edit
    @game = Game.find(params[:id])
  end 

  def new
    @game = Game.new
  end

  def update
    @game = Game.find(params[:id])
    @game.update(:game_info => params[:game][:game_info], :game_time => params[:game][:game_time], :game_date => params[:game][:game_date], :location => params[:game][:location])
    @team = @game.team
    redirect_to team_path(@team)
  end 

  def create
    @game = Game.create(:game_info => params[:game][:game_info], :game_time => params[:game][:game_time], :game_date => params[:game][:game_date], :location => params[:game][:location])
    @team = Team.find(params[:game][:team_id].to_i)
    @team.games << @game
    redirect_to team_path(@team)
  end 

  def destroy
    @game = Game.find(params[:id])
    @game.posts.each {|post| Post.destroy(post.id)}
    @game.destroy
    redirect_to current_user
  end

  def game_params
    params.require(:game).permit(:game_time, :game_date, :location, :game_info, :team_id, :user_id)
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    if params[:post] 
      if params[:post][:sport_id]
        posts = Post.all
        @posts = posts.select do |post|
          post.game.team.sport.id == params[:post][:sport_id].to_i
        end 
      else
        @posts = Post.all
      end 
    else
      @posts = Post.all
    end 
  end

  def create
    @game = Game.where(:game_info => params[:posts_attending][:game_info])
    @user = current_user
    @post = Post.where(:title => params[:posts_attending][:game_info])
    if @post.length > 1
      Post.destroy(@post[0].id)
    else
      Post.destroy(@post[0].id)
    end

    if @user.games_not_attending.include?(@game[0].id.to_s)
      @user.games_not_attending.delete(@game[0].id.to_s)
    end 
    @user.games << @game
    @user.save
    redirect_to current_user
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def edit
    @team = Team.where(:hex_id => params[:team_id][:id]).first
    @user = User.find(params[:id])
    if !@team.users.include?(@user)
      @team.users << @user
      @team.roster_emails << @user.email
      @team.save
      redirect_to team_path(@team) 
    else
      redirect_to user_path(@user) 
    end
  end

  def new
    @team = Team.new
    @user = current_user
  end

  def create

    # @user = User.find(params[:team][:user_id].to_i)
    @user = current_user
    @team = Team.create(name: params[:team][:name])

    
    @team.hex_id = @team.random_id

    @user.teams << @team

    # params[:team][:roster] << @user.email
    @team.roster_emails << params[:team][:roster]
    @team.roster_emails.flatten!

    @sport = Sport.find(params[:team][:sport_id])
    @team.sport = @sport

    @team.save

    # Send email to all emails included in roster in team creation
    @team.roster_emails.each do |email_address|
      UserMailer.roster_email(email_address).deliver_now
    end
    
    redirect_to team_path(@team)
  end 

  def show
    @team = Team.find(params[:id])
    @game = Game.new
    @games = @team.games
  end 

  def destroy
    @team = Team.find(params[:id])
    @team.games.each do |game|
      game.posts.each do |post|
        post.destroy
      end
      game.destroy
    end
    @team.destroy
    redirect_to current_user
  end

  private
  def team_params
    params.require(:team).permit(:name, :roster => [], :sport => [])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to current_user
  end 

  def create
  end 

  def show
    @user = User.find(params[:id])
    games = @user.teams.map do |team|
                team.games.map do |game|
                  game
                end 
             end 
    @games = games.flatten
    @games << @user.games
    @games = @games.flatten
    @games = @games.uniq
  end 

  def update
    @user = User.find(params[:id])
    @game = Game.where(:game_info => params[:games_not_attending][:game_info])
    @user.games_not_attending << @game[0].id
    @user.save

    @post = Post.create(:title => @game[0].game_info)
    @user.posts << @post
    @game[0].posts << @post
    redirect_to current_user
  end 
  # private
  # def user_params
  #   params.require(:user).permit(:user => [:name, :age, :height, :weight, :bio])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/edit.html.erb
<div class="edit_game_form">
  <%= form_for @game, url: game_path do |f| %>
    <%= f.label :game_info, "Game Information" %><br>
    <%= f.text_area :game_info %><br>
    <%= f.label :game_tame, "Game Date" %><br>
    <input type="text" value=<%=@game.game_date%> name="game[game_date]" id="game_date"><br><br>
    <%= f.label :game_tame, "Game Time" %><br>
    <input type="text" value=<%=@game.game_time.strftime("%I:%M%p")%> name="game[game_time]" id="game_time"><br><br>
    <%= f.label :location, "Location" %><br>
    <input type="text" value=<%=@game.location%> name="game[location]" id="game_location"><br><br>
    <input type="submit" value="Update Game">
  <% end %>
</div>

app/views/games/new.html.erb
<%= form_for @game, url: new_game_path do |f| %>
  <%= f.label :game_info, "Game Information" %><br>
  <%= f.text_area :game_info %><br>
  <%= f.submit %>
<% end %>

app/views/posts/_attendingPostedGame.html.erb
<div class='attending_container'>
  <div class='attending_post'>
    <%= form_tag({controller: "posts", action: "create"}, method: "post") do |f|%>
      <input type="text" value="" name="posts_attending[game_info]" class="posts_attending_game_info"><br>
      <input type="submit" value="Join Game">
    <% end %>
  </div>
</div>

app/views/posts/_nav.html.erb
<div class="nav_bar">
  <div class="free_agnt_container">
    <div class="free_agnt">Free Agnt</div>
  </div>
  <div class="icons">
    <div class="posts_icon">
    <%= link_to('Posts', posts_path, :method => :get) %>
    </div>
    <div class="expand_icon_container">
      <img class="expand_icon" src="http://oi59.tinypic.com/fkqsjm.jpg">
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render partial: "nav.html" %>
<div class="user_container">
<!-- NAV DROPDOWN WITH USERS TEAM -->
<div class="user_name_container">
  <div class="user_name">Game Postings</div>
</div>
<div class="nav_dropdown">
  <div class="nav_tile">
    <div><%= link_to "Dashboard", current_user %></div>
    <div><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></div>
  </div>
</div>
</div>

<div class="posts_container">
  <div class="open_spots">
  <div class="open_spots_text">
    <h1>Open Spots</h1>
    <%= link_to "All Posts", posts_path %>
    <%= form_tag({controller: "posts", action: "index"}, method: "get") do |f|%>
    <%= collection_select(:post, :sport_id, Sport.all, :id, :name, prompt: true) %>
    <input type="submit" value="Filter">
    <% end %>
  </div>
  </div>
  <div class="posts">
    <% @posts.each do |post| %>
      <div><li class='add_post'>
      <div>
        <div class="post_title"><%= post.title %></div>
        <ul>
          <li><strong>Team:</strong> <%= post.game.team.name %></li>
          <li><strong>Game Date:</strong> <%= post.game.game_date %></li>
          <li><strong>Game Time:</strong> <%= post.game.game_time.strftime("%I:%M%p") %></li>
          <li><strong>Location:</strong> <%= post.game.location %></li>
          <img class=<%= post.game.team.sport.name+'_post' %> src="">
        </ul>
      </div>
      <%= render partial: "attendingPostedGame.html" %></li></div>
    <% end %> 
  </div> 
</div>